ofile: "hists2017.root"
filesIn:
  # files : ["bbbbNtuple_94.root","bbbbNtuple_95.root", "bbbbNtuple_96.root"]
  dir : "root://cmseos.fnal.gov//store/user/agrummer/bbbb_ntuples/fullSubmission_2017_v27/SKIM_BTagCSV_Data/output/"
  files :
    - "bbbbNtuple_0.root"
    - "bbbbNtuple_1.root"
    - "bbbbNtuple_2.root"
    - "bbbbNtuple_3.root"
    - "bbbbNtuple_4.root"
    - "bbbbNtuple_5.root"
    - "bbbbNtuple_6.root"
    - "bbbbNtuple_7.root"
    - "bbbbNtuple_8.root"
    - "bbbbNtuple_9.root"
    - "bbbbNtuple_10.root"
    - "bbbbNtuple_11.root"
    - "bbbbNtuple_12.root"
    - "bbbbNtuple_13.root"
    - "bbbbNtuple_14.root"
    - "bbbbNtuple_15.root"
    - "bbbbNtuple_16.root"
    - "bbbbNtuple_17.root"
    - "bbbbNtuple_18.root"
    - "bbbbNtuple_19.root"
    - "bbbbNtuple_20.root"
    - "bbbbNtuple_21.root"
    - "bbbbNtuple_22.root"
    - "bbbbNtuple_23.root"
    - "bbbbNtuple_24.root"
    - "bbbbNtuple_25.root"
    - "bbbbNtuple_26.root"
    - "bbbbNtuple_27.root"
    - "bbbbNtuple_28.root"
    - "bbbbNtuple_29.root"
    - "bbbbNtuple_30.root"
    - "bbbbNtuple_31.root"
    - "bbbbNtuple_32.root"
    - "bbbbNtuple_33.root"
    - "bbbbNtuple_34.root"
    - "bbbbNtuple_35.root"
    - "bbbbNtuple_36.root"
    - "bbbbNtuple_37.root"
    - "bbbbNtuple_38.root"
    - "bbbbNtuple_39.root"
    - "bbbbNtuple_40.root"
    - "bbbbNtuple_41.root"
    - "bbbbNtuple_42.root"
    - "bbbbNtuple_43.root"
    - "bbbbNtuple_44.root"
    - "bbbbNtuple_45.root"
    - "bbbbNtuple_46.root"
    - "bbbbNtuple_47.root"
    - "bbbbNtuple_48.root"
    - "bbbbNtuple_49.root"
    - "bbbbNtuple_50.root"
    - "bbbbNtuple_51.root"
    - "bbbbNtuple_52.root"
    - "bbbbNtuple_53.root"
    - "bbbbNtuple_54.root"
    - "bbbbNtuple_55.root"
    - "bbbbNtuple_56.root"
    - "bbbbNtuple_57.root"
    - "bbbbNtuple_58.root"
    - "bbbbNtuple_59.root"
    - "bbbbNtuple_60.root"
    - "bbbbNtuple_61.root"
    - "bbbbNtuple_62.root"
    - "bbbbNtuple_63.root"
    - "bbbbNtuple_64.root"
    - "bbbbNtuple_65.root"
    - "bbbbNtuple_66.root"
    - "bbbbNtuple_67.root"
    - "bbbbNtuple_68.root"
    - "bbbbNtuple_69.root"
    - "bbbbNtuple_70.root"
    - "bbbbNtuple_71.root"
    - "bbbbNtuple_72.root"
    - "bbbbNtuple_73.root"
    - "bbbbNtuple_74.root"
    - "bbbbNtuple_75.root"
    - "bbbbNtuple_76.root"
    - "bbbbNtuple_77.root"
    - "bbbbNtuple_78.root"
    - "bbbbNtuple_79.root"
    - "bbbbNtuple_80.root"
    - "bbbbNtuple_81.root"
    - "bbbbNtuple_82.root"
    - "bbbbNtuple_83.root"
    - "bbbbNtuple_84.root"
    - "bbbbNtuple_85.root"
    - "bbbbNtuple_86.root"
    - "bbbbNtuple_87.root"
    - "bbbbNtuple_88.root"
    - "bbbbNtuple_89.root"
    - "bbbbNtuple_90.root"
    - "bbbbNtuple_91.root"
    - "bbbbNtuple_92.root"
    - "bbbbNtuple_93.root"
    - "bbbbNtuple_94.root"
    - "bbbbNtuple_94.root"
    - "bbbbNtuple_95.root"
    - "bbbbNtuple_95.root"
    - "bbbbNtuple_96.root"
    - "bbbbNtuple_97.root"
    - "bbbbNtuple_98.root"
    - "bbbbNtuple_99.root"
    - "bbbbNtuple_100.root"
    - "bbbbNtuple_101.root"
    - "bbbbNtuple_102.root"
    - "bbbbNtuple_103.root"
    - "bbbbNtuple_104.root"
    - "bbbbNtuple_105.root"
    - "bbbbNtuple_106.root"
    - "bbbbNtuple_107.root"
    - "bbbbNtuple_108.root"
    - "bbbbNtuple_109.root"
    - "bbbbNtuple_110.root"
    - "bbbbNtuple_111.root"
    - "bbbbNtuple_112.root"
    - "bbbbNtuple_113.root"
    - "bbbbNtuple_114.root"
    - "bbbbNtuple_115.root"
    - "bbbbNtuple_116.root"
    - "bbbbNtuple_117.root"
    - "bbbbNtuple_118.root"
    - "bbbbNtuple_119.root"
