cd scripts && g++  -std=c++17 -I `root-config --incdir` -o Unroll2DplotsSubRangeValidationTest Unroll2DplotsSubRangeValidationTest.cc `root-config --libs` -O3 ; cd -

./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_$1_v34_bkgValidation/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ValidationRegionBlinded
./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_$1_v34_bkgValidation/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ValidationRegionBlinded
./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_$1_v34_bkgValidation/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ValidationRegionBlinded
./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_$1_v34_bkgValidation/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ValidationRegionBlinded
./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_$1_v34_bkgValidation/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ValidationRegionBlinded

# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_2017_v33_bkgValidation/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_2017_v33_bkgValidation/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_2017_v33_bkgValidation/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_2017_v33_bkgValidation/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_2017_v33_bkgValidation/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ValidationRegionBlinded

# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_2018_v33_bkgValidation/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_2018_v33_bkgValidation/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_2018_v33_bkgValidation/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_2018_v33_bkgValidation/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_2018_v33_bkgValidation/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ValidationRegionBlinded

