cd scripts && g++  -std=c++17 -I `root-config --incdir` -o Unroll2DplotsSubRangeControlTest Unroll2DplotsSubRangeControlTest.cc `root-config --libs` -O3 ; cd -

./scripts/Unroll2DplotsSubRangeControlTest $1DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan_2021Dec15/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ControlRegionBlinded
./scripts/Unroll2DplotsSubRangeControlTest $1DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan_2021Dec15/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ControlRegionBlinded
./scripts/Unroll2DplotsSubRangeControlTest $1DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan_2021Dec15/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ControlRegionBlinded
./scripts/Unroll2DplotsSubRangeControlTest $1DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan_2021Dec15/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ControlRegionBlinded
./scripts/Unroll2DplotsSubRangeControlTest $1DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan_2021Dec15/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ControlRegionBlinded

# ./scripts/Unroll2DplotsSubRangeTest 2017DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan2017_v33_bkg/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeTest 2017DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan2017_v33_bkg/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeTest 2017DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan2017_v33_bkg/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeTest 2017DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan2017_v33_bkg/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeTest 2017DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan2017_v33_bkg/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ControlRegionBlinded

# ./scripts/Unroll2DplotsSubRangeTest 2017DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan2018_v33_bkg/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeTest 2017DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan2018_v33_bkg/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeTest 2017DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan2018_v33_bkg/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeTest 2017DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan2018_v33_bkg/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeTest 2017DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan2018_v33_bkg/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ControlRegionBlinded

