cd scripts && g++  -std=c++17 -I `root-config --incdir` -o Unroll2DplotsSubRangeValidationTest Unroll2DplotsSubRangeValidationTest.cc `root-config --libs` -O3 ; cd -

# # using normal bins:
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_$1_v34_aidan_2022Jan26_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_$1_v34_aidan_2022Jan26_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_$1_v34_aidan_2022Jan26_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_$1_v34_aidan_2022Jan26_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_$1_v34_aidan_2022Jan26_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ValidationRegionBlinded

# for rebinned data:
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_$1_v34_aidan_rebinnned_2021Dec23_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_$1_v34_aidan_rebinnned_2021Dec23_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_$1_v34_aidan_rebinnned_2021Dec23_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_$1_v34_aidan_rebinnned_2021Dec23_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_$1_v34_aidan_rebinnned_2021Dec23_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ValidationRegionBlinded

# # normal bins, single point:
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_$1_v34_aidan_2022Jan26_VR_mx600_my400/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_$1_v34_aidan_2022Jan26_VR_mx600_my400/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_$1_v34_aidan_2022Jan26_VR_mx600_my400/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_$1_v34_aidan_2022Jan26_VR_mx600_my400/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_$1_v34_aidan_2022Jan26_VR_mx600_my400/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ValidationRegionBlinded

# normal bins, single point, BDT masswindow training:
# ./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/VR/$1DataPlots_2022Feb8_BDTmasscut_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/VR/$1DataPlots_2022Feb8_BDTmasscut_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/VR/$1DataPlots_2022Feb8_BDTmasscut_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/VR/$1DataPlots_2022Feb8_BDTmasscut_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/VR/$1DataPlots_2022Feb8_BDTmasscut_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/VR/$1DataPlots_2022Feb8_BDTmasscut_ptX_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/VR/$1DataPlots_2022Feb8_BDTmasscut_ptX_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/VR/$1DataPlots_2022Feb8_BDTmasscut_ptX_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/VR/$1DataPlots_2022Feb8_BDTmasscut_ptX_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/VR/$1DataPlots_2022Feb8_BDTmasscut_ptX_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ValidationRegionBlinded

# normal bins, single point, BDT masswindow training:
# ./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/$1DataPlots_2022Mar2_only_mXmY_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/$1DataPlots_2022Mar2_only_mXmY_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/$1DataPlots_2022Mar2_only_mXmY_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/$1DataPlots_2022Mar2_only_mXmY_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/$1DataPlots_2022Mar2_only_mXmY_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/$1DataPlots_2022Mar2_without_mXmY_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/$1DataPlots_2022Mar2_without_mXmY_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/$1DataPlots_2022Mar2_without_mXmY_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/$1DataPlots_2022Mar2_without_mXmY_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/$1DataPlots_2022Mar2_without_mXmY_VR/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ValidationRegionBlinded

# # Full BDT, mass window, ttbar, data
# ./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/$1DataPlots_2022Mar17_fullBDT_TTBAR_MassWindow_data/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/$1DataPlots_2022Mar17_fullBDT_TTBAR_MassWindow_data/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/$1DataPlots_2022Mar17_fullBDT_TTBAR_MassWindow_data/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/$1DataPlots_2022Mar17_fullBDT_TTBAR_MassWindow_data/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/$1DataPlots_2022Mar17_fullBDT_TTBAR_MassWindow_data/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ValidationRegionBlinded

# april 6 - check on the errors...
./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/$1DataPlots_$2/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ValidationRegionBlinded
./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/$1DataPlots_$2/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ValidationRegionBlinded
./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/$1DataPlots_$2/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ValidationRegionBlinded
./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/$1DataPlots_$2/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ValidationRegionBlinded
./scripts/Unroll2DplotsSubRangeValidationTest VarPlots/rootHists/$1DataPlots_$2/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ValidationRegionBlinded

# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_2017_v33_bkgValidation/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_2017_v33_bkgValidation/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_2017_v33_bkgValidation/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_2017_v33_bkgValidation/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_2017_v33_bkgValidation/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ValidationRegionBlinded

# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_2018_v33_bkgValidation/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_2018_v33_bkgValidation/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_2018_v33_bkgValidation/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_2018_v33_bkgValidation/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ValidationRegionBlinded
# ./scripts/Unroll2DplotsSubRangeValidationTest DataPlots_fullSubmission_2018_v33_bkgValidation/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ValidationRegionBlinded

