cd scripts && g++  -std=c++17 -I `root-config --incdir` -o Unroll2DplotsSubRangeControlTest Unroll2DplotsSubRangeControlTest.cc `root-config --libs` -O3 ; cd -

# using normal bins:
# ./scripts/Unroll2DplotsSubRangeControlTest DataPlots_fullSubmission_$1_v34_aidan_2022Jan26/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest DataPlots_fullSubmission_$1_v34_aidan_2022Jan26/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest DataPlots_fullSubmission_$1_v34_aidan_2022Jan26/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest DataPlots_fullSubmission_$1_v34_aidan_2022Jan26/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest DataPlots_fullSubmission_$1_v34_aidan_2022Jan26/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ControlRegionBlinded

# for rebinned data:
# ./scripts/Unroll2DplotsSubRangeControlTest DataPlots_fullSubmission_$1_v34_aidan_rebinnned_2021Dec23/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest DataPlots_fullSubmission_$1_v34_aidan_rebinnned_2021Dec23/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest DataPlots_fullSubmission_$1_v34_aidan_rebinnned_2021Dec23/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest DataPlots_fullSubmission_$1_v34_aidan_rebinnned_2021Dec23/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest DataPlots_fullSubmission_$1_v34_aidan_rebinnned_2021Dec23/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ControlRegionBlinded

# normal bins, single point, BDT masswindow training:
# ./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_2022Feb8_BDTmasscut/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_2022Feb8_BDTmasscut/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_2022Feb8_BDTmasscut/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_2022Feb8_BDTmasscut/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_2022Feb8_BDTmasscut/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_2022Feb8_BDTmasscut_ptX/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_2022Feb8_BDTmasscut_ptX/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_2022Feb8_BDTmasscut_ptX/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_2022Feb8_BDTmasscut_ptX/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_2022Feb8_BDTmasscut_ptX/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ControlRegionBlinded

# # normal bins, single point, BDT masswindow training:
# ./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_2022Mar2_only_mXmY/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_2022Mar2_only_mXmY/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_2022Mar2_only_mXmY/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_2022Mar2_only_mXmY/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_2022Mar2_only_mXmY/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_2022Mar2_without_mXmY/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_2022Mar2_without_mXmY/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_2022Mar2_without_mXmY/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_2022Mar2_without_mXmY/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_2022Mar2_without_mXmY/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ControlRegionBlinded

# # Full BDT, mass window, ttbar, data
# ./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_2022Mar17_fullBDT_TTBAR_MassWindow_data/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_2022Mar17_fullBDT_TTBAR_MassWindow_data/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_2022Mar17_fullBDT_TTBAR_MassWindow_data/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_2022Mar17_fullBDT_TTBAR_MassWindow_data/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_2022Mar17_fullBDT_TTBAR_MassWindow_data/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ControlRegionBlinded

# Full BDT, mass window, ttbar, data
./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_$2/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ControlRegionBlinded
./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_$2/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ControlRegionBlinded
./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_$2/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ControlRegionBlinded
./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_$2/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ControlRegionBlinded
./scripts/Unroll2DplotsSubRangeControlTest VarPlots/rootHists/$1DataPlots_$2/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ControlRegionBlinded

# ./scripts/Unroll2DplotsSubRangeControlTest $1DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan_2021Dec15/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest $1DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan_2021Dec15/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest $1DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan_2021Dec15/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest $1DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan_2021Dec15/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeControlTest $1DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan_2021Dec15/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ControlRegionBlinded

# ./scripts/Unroll2DplotsSubRangeTest 2017DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan2017_v33_bkg/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeTest 2017DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan2017_v33_bkg/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeTest 2017DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan2017_v33_bkg/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeTest 2017DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan2017_v33_bkg/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeTest 2017DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan2017_v33_bkg/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ControlRegionBlinded

# ./scripts/Unroll2DplotsSubRangeTest 2017DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan2018_v33_bkg/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 0 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeTest 2017DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan2018_v33_bkg/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 1 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeTest 2017DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan2018_v33_bkg/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 2 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeTest 2017DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan2018_v33_bkg/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 3 selectionbJets_ControlRegionBlinded
# ./scripts/Unroll2DplotsSubRangeTest 2017DataPlots_NMSSM_XYH_bbbb_dataDrivenStudies_aidan2018_v33_bkg/outPlotter.root data_BTagCSV_dataDriven_kinFit selectionbJets_SignalRegion HH_kinFit_m_H2_m 0 4 selectionbJets_ControlRegionBlinded

